apps/crud_simulador/urls.py
from django.conf.urls import url
from apps.crud_simulador.views import perfilCreate, perfilList, perfilUpdate, perfilDelete, perfilShow, search, mocvCreate,mocvList,mocvDelete,mocvShow,mocvUpdate,buscarxd\
    ,datos_empresaCreate, datos_empresaList, datos_empresaDelete, datos_empresaUpdate,datos_empresaShow, searchluis, manoObraCreate,manoObralist,manoObraDelete,manoObraUpdate\
    ,manoObraShow,conceptoCrecimientoDemandaCreate,conceptoCrecimientoDemandalist,conceptoCrecimientoDemandaDelete,conceptoCrecimientoDemandaUpdate, conceptoCrecimientoDemandaShow, searchluis2, searchluis3,\
    estimacion_serviciosCreate, estimacion_serviciosList,estimacion_serviciosDelete,estimacion_serviciosUpdate,estimacion_serviciosShow, tipoGastoOperativoCreate, tipoGastoOperativoList, tipoGastoOperativoDelete, tipoGastoOperativoUpdate, tipoGastoOperativoShow, searchever, searchever1\
    ,costosCreate,costosList,costosDelete,costosUpdate,costosShow,searchc,gastosCreate,gastosList,gastosDelete,gastosUpdate,gastosShow,findg\
    ,productoCreate,productoList,productoDelete,productoUpdate,productoShow,buscaP,gastossCreate,gastossList,gastossDelete,gastossUpdate,gastossShow,search_g\
    ,crecimientoDemandaCreate,crecimientoDemandaList,crecimientoDemandaDelete,crecimientoDemandaUpdate,crecimientoDemandaShow,search_c\
    ,tipoUsuarioCreate,tipoUsuarioList,tipoUsuarioDelete,tipoUsuarioUpdate,tipoUsuarioShow, search_u,gastosIndirectosCreate,gastosIndirectosList,gastosIndirectosDelete,gastosIndirectosUpdate,gastosIndirectosShow,search_a\
    ,tiposGastoscreate,tiposGastosList,tiposGastosDelete,tiposGastosUpdate,tiposGastosShow,search_b,usuarioCreate,usuarioList,usuarioDelete,usuarioShow,usuarioUpdate,search_tg, materiaPrimaCreate, materiaPrimaList,materiaPrimaDelete,materiaPrimaShow,materiaPrimaUpdate,search_ma,estimacionCreate\
    ,estimacionList,estimacionDelete,estimacionShow,estimacionUpdate,search_es,tiposInversionesCreate,tiposInversionesList,tiposInversionesDelete,tiposInversionesUpdate,tiposInversionesShow,search_ti

urlpatterns = [
    #urls de alex perfil usuario y mano de obra comision venta
    url(r'^crear/', perfilCreate.as_view(), name='perfil_crear'),
    url(r'^listar/', perfilList.as_view(), name='perfil_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', perfilDelete.as_view(), name='perfil_eliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', perfilUpdate.as_view(), name='perfil_modificar'),
    url(r'^mostrar/(?P<pk>\d+)/$', perfilShow.as_view(), name='perfil_mostrar'),
    url(r'^buscar/$', search, name='perfil_buscar'),

    url(r'^create/',mocvCreate.as_view(), name='mocv_create'),
    url(r'^list/', mocvList.as_view(), name='mocv_list'),
    url(r'^delete/(?P<pk>\d+)/$', mocvDelete.as_view(), name='mocv_delete'),
    url(r'^update/(?P<pk>\d+)/$', mocvUpdate.as_view(), name='mocv_update'),
    url(r'^show/(?P<pk>\d+)/$', mocvShow.as_view(), name='mocv_show'),
    url(r'^search/$', buscarxd, name='mocv_search'),

    #urls de luis david
    url(r'^crearempresa/', datos_empresaCreate.as_view(), name='datos_empresa_crear'),
    url(r'^listarempresa/', datos_empresaList.as_view(), name='datos_empresa_listar'),
    url(r'^eliminarempresa/(?P<pk>\d+)/$', datos_empresaDelete.as_view(), name='datos_empresa_eliminar'),
    url(r'^editarempresa/(?P<pk>\d+)/$', datos_empresaUpdate.as_view(), name='datos_empresa_editar'),
    url(r'^mostrarempresa/(?P<pk>\d+)/$', datos_empresaShow.as_view(), name='datos_empresa_mostrar'),
    url(r'^buscarempresa/$', searchluis, name='datos_empresa_buscar'),

    url(r'^crearobra/', manoObraCreate.as_view(), name='manoObra_crear'),
    url(r'^guardarobra/', manoObralist.as_view(), name='manoObra_listar'),
    url(r'^eliminarobra/(?P<pk>\d+)/$', manoObraDelete.as_view(), name='manoObra_eliminar'),
    url(r'^modificarobra/(?P<pk>\d+)/$', manoObraUpdate.as_view(), name='manoObra_editar'),
    url(r'^observarobra/(?P<pk>\d+)/$', manoObraShow.as_view(), name='manoObra_mostrar'),
    url(r'^investigarobra/$', searchluis2, name='manoObra_buscar'),

    url(r'^nuevosccd/', conceptoCrecimientoDemandaCreate.as_view(), name='conceptoCrecimientoDemanda_crear'),
    url(r'^listasccd/', conceptoCrecimientoDemandalist.as_view(), name='conceptoCrecimientoDemanda_listar'),
    url(r'^eliminacionccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaDelete.as_view(), name='conceptoCrecimientoDemanda_eliminar'),
    url(r'^modificacionccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaUpdate.as_view(), name='conceptoCrecimientoDemanda_editar'),
    url(r'^verccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaShow.as_view(), name='conceptoCrecimientoDemanda_mostrar'),
    url(r'^buscadorccd/$', searchluis3, name='conceptoCrecimientoDemanda_buscar'),

    #Urls de Everardo
    url(r'^nuevoservicio/', estimacion_serviciosCreate.as_view(), name='estimacion_servicio_crear'),
    url(r'^listarservicio/', estimacion_serviciosList.as_view(), name='estimacion_servicio_listar'),
    url(r'^eliminarservicio/(?P<pk>\d+)/$', estimacion_serviciosDelete.as_view(), name='estimacion_servicio_eliminar'),
    url(r'^modificarservicio/(?P<pk>\d+)/$', estimacion_serviciosUpdate .as_view(), name='estimacion_servicio_editar'),
    url(r'^mostrarservicio/(?P<pk>\d+)/$', estimacion_serviciosShow.as_view(), name='estimacion_servicio_mostrar'),
    url(r'^buscarservicio/', searchever, name='estimacion_servicio_buscar'),

    url(r'^newtgasto/',tipoGastoOperativoCreate.as_view(), name='tipoGastoOperativo_crear'),
    url(r'^listgasto/',tipoGastoOperativoList.as_view(), name='tipoGastoOperativo_listar'),
    url(r'^deletegasto/(?P<pk>\d+)/$',tipoGastoOperativoDelete.as_view(), name='tipoGastoOperativo_eliminar'),
    url(r'^updategasto/(?P<pk>\d+)/$',tipoGastoOperativoUpdate.as_view(), name='tipoGastoOperativo_editar'),
    url(r'^showgasto/(?P<pk>\d+)/$',tipoGastoOperativoShow.as_view(), name='tipoGastoOperativo_mostrar'),
    url(r'^searchgasto/$', searchever1, name='tipoGastoOperativo_buscar'),

 #urls de carmen
    url(r'^nuevoC/', costosCreate.as_view(), name='costos_crear'),
    url(r'^listarC/', costosList.as_view(), name='costos_listar'),
    url(r'^eliminarC/(?P<pk>\d+)/$', costosDelete.as_view(), name='costos_eliminar'),
    url(r'^modificarC/(?P<pk>\d+)/$', costosUpdate.as_view(), name='costos_editar'),
    url(r'^mostrarC/(?P<pk>\d+)/$', costosShow.as_view(), name='costos_mostrar'),
    url(r'^buscarC/$', searchc, name='costos_buscar'),

    url(r'^nuevoG/', gastosCreate.as_view(), name='gastos_crear'),
    url(r'^listarG/', gastosList.as_view(), name='gastos_listar'),
    url(r'^eliminarG/(?P<pk>\d+)/$', gastosDelete.as_view(), name='gastos_eliminar'),
    url(r'^modificarG/(?P<pk>\d+)/$', gastosUpdate.as_view(), name='gastos_editar'),
    url(r'^mostrarG/(?P<pk>\d+)/$', gastosShow.as_view(), name='gastos_mostrar'),
    url(r'^buscarG/$', findg, name='gastos_buscar'),

    url(r'^nuevoP/', productoCreate.as_view(), name='producto_crear'),
    url(r'^listarP/', productoList.as_view(), name='producto_listar'),
    url(r'^eliminarP/(?P<pk>\d+)/$', productoDelete.as_view(), name='producto_eliminar'),
    url(r'^modificarP/(?P<pk>\d+)/$', productoUpdate.as_view(), name='producto_editar'),
    url(r'^mostrarP/(?P<pk>\d+)/$', productoShow.as_view(), name='producto_mostrar'),
    url(r'^buscarP/$', buscaP, name='producto_buscar'),

#Urls de Alan
    url(r'^nuevogastos/',gastossCreate.as_view(), name='gastoss_crear'),
    url(r'^listargastos/',gastossList.as_view(),name='gastoss_listar'),
    url(r'^eliminargastos/(?P<pk>\d+)/$', gastossDelete.as_view(), name='gastoss_eliminar'),
    url(r'^editargastos/(?P<pk>\d+)/$', gastossUpdate.as_view(), name='gastoss_editar'),
    url(r'^mostrargastos/(?P<pk>\d+)/$', gastossShow.as_view(), name='gastoss_mostrar'),
    url(r'^buscargastos/$', search_g, name='gastoss_buscar'),

    url(r'^newcrecimiento/',crecimientoDemandaCreate.as_view(), name='crecimientoDemanda_crear'),
    url(r'^listcrecimiento/',crecimientoDemandaList.as_view(),name='crecimientoDemanda_listar'),
    url(r'^deletecrecimiento/(?P<pk>\d+)/$', crecimientoDemandaDelete.as_view(), name='crecimientoDemanda_eliminar'),
    url(r'^updatecrecimiento/(?P<pk>\d+)/$', crecimientoDemandaUpdate.as_view(), name='crecimientoDemanda_editar'),
    url(r'^showcrecimiento/(?P<pk>\d+)/$', crecimientoDemandaShow.as_view(), name='crecimientoDemanda_mostrar'),
    url(r'^searchcrecimiento/$', search_c, name='crecimientoDemanda_buscar'),

    url(r'^nuevostipou/',tipoUsuarioCreate.as_view(), name='tipoUsuario_crear'),
    url(r'^listastipou/',tipoUsuarioList.as_view(),name='tipoUsuario_listar'),
    url(r'^eliminaciontipou/(?P<pk>\d+)/$', tipoUsuarioDelete.as_view(), name='tipoUsuario_eliminar'),
    url(r'^modificartipou/(?P<pk>\d+)/$', tipoUsuarioUpdate.as_view(), name='tipoUsuario_editar'),
    url(r'^vertipou/(?P<pk>\d+)/$', tipoUsuarioShow.as_view(), name='tipoUsuario_mostrar'),
    url(r'^buscadortipou/$', search_u, name='tipoUsuario_buscar'),

#Urls de Emmanuel

url(r'^nuevoGI/', gastosIndirectosCreate.as_view(), name='gastosIndirectos_crear'),
    url(r'^listaGI/', gastosIndirectosList.as_view(), name='gastosIndirectos_listar'),
    url(r'^eliminarGI/(?P<pk>\d+)/$', gastosIndirectosDelete.as_view(), name='gastosIndirectos_eliminar'),
    url(r'^editaGI/(?P<pk>\d+)/$', gastosIndirectosUpdate.as_view(), name='gastosIndirectos_editar'),
    url(r'^mostrarGI/(?P<pk>\d+)/$', gastosIndirectosShow.as_view(), name='gastosIndirectos_mostrar'),
    url(r'^buscarGI/$', search_a, name='gastosIndirectos_buscar'),

    url(r'^nuevostg/', tiposGastoscreate.as_view(), name='tiposGastos_crear'),
    url(r'^listartg/', tiposGastosList.as_view(), name='tiposGastos_listar'),
    url(r'^eliminarrtg/(?P<pk>\d+)/$', tiposGastosDelete.as_view(), name='tiposGastos_eliminar'),
    url(r'^editartg/(?P<pk>\d+)/$', tiposGastosUpdate.as_view(), name='tiposGastos_editar'),
    url(r'^mostratg/(?P<pk>\d+)/$', tiposGastosShow.as_view(), name='tiposGastos_mostrar'),

simulador/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^perfil/', include(('apps.crud_simulador.urls', 'apps'), namespace='perfil_usuario')),
    url(r'^mcomisiones/', include(('apps.crud_simulador.urls', 'apps'), namespace='mcomisiones')),

    #urls de luis xD
    url(r'^datos_empresa/',include(('apps.crud_simulador.urls', 'apps'), namespace='datos_empresa')),
    url(r'^manoObra/',include(('apps.crud_simulador.urls', 'apps'), namespace='manoObra')),
    url(r'^demanda/',include(('apps.crud_simulador.urls', 'apps'), namespace='demanda')),

    #urls de Ever xD
    url(r'^estimacion_servicios/', include(('apps.crud_simulador.urls', 'apps'), namespace='estimacion_servicios')),
    url(r'^tipoGastoOperativo/', include(('apps.crud_simulador.urls', 'apps'), namespace='tipoGastoOperativo')),

 #urls de carmen
    url(r'^costos/', include(('apps.crud_simulador.urls', 'apps'), namespace='costos')),
    url(r'^gastos/', include(('apps.crud_simulador.urls', 'apps'), namespace='gastos')),
    url(r'^producto/', include(('apps.crud_simulador.urls', 'apps'), namespace='producto')),
   #Urls de Alan
    url(r'^gastoss/',include(('apps.crud_simulador.urls','apps',),namespace='gastoss')),
    url(r'^crecimientoDemanda/', include(('apps.crud_simulador.urls', 'apps',), namespace='crecimientoDemanda')),
    url(r'^tipoUsuario/', include(('apps.crud_simulador.urls', 'apps',), namespace='tipoUsuario')),

#urls de Emmanuel

    url(r'^gastosIndirectos/', include(('apps.crud_simulador.urls', 'apps'), namespace='gastosIndirectos')),
    url(r'^usuario/', include(('apps.crud_simulador.urls', 'apps'), namespace='usuario')),
    url(r'^tiposGastos/', include(('apps.crud_simulador.urls', 'apps'), namespace='tiposGastos')),

#urls de aldair
    url(r'^tiposInversiones/', include(('apps.crud_simulador.urls', 'apps'), namespace='tiposInversiones')),
    url(r'^materiaPrima/', include(('apps.crud_simulador.urls', 'apps'), namespace='materiaPrima')),
    url(r'^estimacion/', include(('apps.crud_simulador.urls', 'apps'), namespace='estimacion')),
]

templates/formularios/mocv_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.concepto }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'mcomisiones:mocv_list' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/formularios/mocv_form.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
        <div class="col-md-8 ml-auto mr-auto">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <a class= "btn btn-info btn-round" href="{% url 'mcomisiones:mocv_list' %}"> Cancelar <i class="material-icons right">cancel</i></a>
                <button class="btn btn-danger btn-round" type="submit"> Guardar <i class="material-icons right">send</i></button>
            </form>
        </div>
    </div>
{% endblock %}

templates/formularios/mocv_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-ml-auto mr-auto">
        <table class="table-bordered">
	        <thead>
		        <tr>
                    <td>Id mano de obra comisiones venta: </td>
                    <td>concepto: </td>
                    <td>Ventas Mensuales: </td>
                    <td>Comision: </td>
                    <td>Total Empleado: </td>
                    <td>Costo Anual: </td>
                    <td>Id De La Empresa: </td>
                </tr>
            </thead>
            <tbody>
		        {% if object_list %}
		        {% for manoObraComisionesVenta in object_list %}
		        <tr>
			        <td>{{ manoObraComisionesVenta.idmanoObraComisionesVenta}}</td>
			        <td>{{ manoObraComisionesVenta.concepto }}</td>
			        <td>{{ manoObraComisionesVenta.ventas_mensuales }}</td>
			        <td>{{ manoObraComisionesVenta.comision }}</td>
			        <td>{{ manoObraComisionesVenta.total_empleados }}</td>
			        <td>{{ manoObraComisionesVenta.costo_anual }}</td>
                    <td>{{ manoObraComisionesVenta.datos_empresa_id_empresa }}</td>
                    <td>
                        <a class="btn blue" href="{% url 'mcomisiones:mocv_update' manoObraComisionesVenta.idmanoObraComisionesVenta %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'mcomisiones:mocv_delete' manoObraComisionesVenta.idmanoObraComisionesVenta %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de personas</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

{% endblock%}

templates/formularios/mocv_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-ml-auto mr-auto">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
                id perfil: &nbsp{{ filter.form.idmanoObraComisionesVenta }} &nbsp
                Nombres: &nbsp {{ filter.form.ventas_mensuales }} &nbsp
                <button class="btn btn-success" type="submit">Filtrar</button>
            </p>
        </form>
        <table class="table-bordered">
	        <thead>
		        <tr>>
                    <td>Id MOCV: </td>
                    <td>Concepto: </td>
                    <td>Ventas Mensuales: </td>
                    <td>Comision: </td>
                    <td>Total Empleados: </td>
                    <td>Costo Anual: </td>
                    <td>Datos Empresa Id Empresa: </td>
            </thead>
            <tbody>
            {% if object_list %}
		        {% for manoObraComisionesVenta in object_list %}
		        <tr>
			        <td>{{ manoObraComisionesVenta.idmanoObraComisionesVenta }}</td>
			        <td>{{ manoObraComisionesVenta.concepto }}</td>
			        <td>{{ manoObraComisionesVenta.ventas_mensuales }}</td>
			        <td>{{ manoObraComisionesVenta.comision }}</td>
			        <td>{{ manoObraComisionesVenta.total_empleados }}</td>
			        <td>{{ manoObraComisionesVenta.costo_anual }}</td>
                    <td>{{ manoObraComisionesVenta.datos_empresa_id_empresa }}</td>
			        <td>
				        <a class="btn btn-success" href="{% url 'mcomisiones:mocv_show' manoObraComisionesVenta.idmanoObraComisionesVent %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn btn-info" href="{% url 'mcomisiones:mocv_update' manoObraComisionesVenta.idmanoObraComisionesVent %}"><i class="material-icons">create</i></a>
                        <a class="btn btn-danger" href="{% url 'mcomisiones:mocv_delete' manoObraComisionesVenta.idmanoObraComisionesVent %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

{% endblock%}

templates/formularios/mocv_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 ml-auto mr-auto">
        <p><strong>Id MOCV: </strong>{{ object.idmanoObraComisionesVenta }} </p>
        <p><strong>Concepto: </strong>{{ object.concepto }} </p>
        <p><strong>Ventas Mensuales: </strong>{{ object.ventas_mensuales }} </p>
        <p><strong>Comision: </strong>{{ object.comision }} </p>
        <p><strong>Total Empleados: </strong>{{ object.total_empleados }} </p>
        <p><strong>Costo Anual: </strong>{{ object.costo_anual }} </p>
        <p><strong>Datos Empresa Id Empresa: </strong>{{ object.datos_empresa_id_empresa }} </p>


        <a class= "btn btn-danger" href="{% url 'mcomisiones:mocv_list' %}">Ok</a>
        <a class= "btn btn-info" href="{% url 'mcomisiones:mocv_update' manoObraComisionesVenta.idmanoObraComisionesVenta %}"><i class="material-icons">create</i></a>
        <a class="btn btn-success" href="{%  url 'mcomisiones:mocv_delete' manoObraComisionesVenta.idmanoObraComisionesVenta %}"><i class="material-icons">delete</i></a>
    </div>
</div>



{% endblock %}

templates/formularios/perfil_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.nombre_usuario }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'perfil_usuario:perfil_listar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/formularios/perfil_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-ml-auto mr-auto">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
                id perfil: &nbsp{{ filter.form.idperfil }} &nbsp
                Nombres: &nbsp {{ filter.form.nombre_usuario }} &nbsp
                <button class="btn btn-success" type="submit">Filtrar</button>
            </p>
        </form>
        <table class="table-bordered">
	        <thead>
		        <tr>>
                    <td>id del usuario: </td>
                    <td>Nombre del usuario: </td>
                    <td>Apellido Paterno: </td>
                    <td>Apellido Materno: </td>
                    <td>RFC Del Usuario: </td>
                    <td>Correo Eletronico: </td>
                    <td>Telefono: </td>
                    <td>Domicilio: </td>
                    <td>Colonia: </td>
                    <td>Codigo Postal: </td>
                    <td>Ciudad: </td>
                    <td>Estado: </td>
                    <td>Usuario: </td>

            </thead>
            <tbody>
            {% if filter.qs %}
                {% for perfil_usuario in filter.qs %}
		        <tr>
			       <td>{{ perfil_usuario.idperfil}}</td>
			        <td>{{ perfil_usuario.nombre_usuario }}</td>
			        <td>{{ perfil_usuario.apellido_p_usuario }}</td>
			        <td>{{ perfil_usuario.apellido_m_usuario }}</td>
			        <td>{{ perfil_usuario.rfc_usuario }}</td>
			        <td>{{ perfil_usuario.email_usuario }}</td>
                    <td>{{ perfil_usuario.telefono_usuario }}</td>
                    <td>{{ perfil_usuario.domicilio_usuario }}</td>
                    <td>{{ perfil_usuario.colonia_usuario }}</td>
                    <td>{{ perfil_usuario.codigo_postal_usuario }}</td>
                    <td>{{ perfil_usuario.ciudad_usuario }}</td>
                    <td>{{ perfil_usuario.estado_usuario }}</td>
                    <td>{{ perfil_usuario.usuario_idusuario }}</td>
			        <td>
				        <a class="btn btn-success" href="{% url 'perfil_usuario:perfil_mostrar' perfil_usuario.idperfil %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn btn-info" href="{% url 'perfil_usuario:perfil_modificar' perfil_usuario.idperfil %}"><i class="material-icons">create</i></a>
                        <a class="btn btn-danger" href="{% url 'perfil_usuario:perfil_eliminar' perfil_usuario.idperfil %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

{% endblock%}

templates/formularios/perfil_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 ml-auto mr-auto">
        <p><strong>id del perfil: </strong>{{ object.idperfil }} </p>
        <p><strong>Nombre del usuario: </strong>{{ object.nombre_usuario }} </p>
        <p><strong>Apellido Paterno: </strong>{{ object.apellido_p_usuario }} </p>
        <p><strong>Apellido Materno: </strong>{{ object.apellido_m_usuario }} </p>
        <p><strong>RFC: </strong>{{ object.rfc_usuario}} </p>
        <p><strong>Correo Eletronico: </strong>{{ object.email_usuario }} </p>
        <p><strong>Numero De Telefono: </strong>{{ object.telefono_usuario}} </p>
        <p><strong>Domicilio: </strong>{{ object.domicilio_usuario}} </p>
        <p><strong>Colonia: </strong>{{ object.colonia_usuario}} </p>
        <p><strong>Codigo Postal: </strong>{{ object.codigo_postal_usuario}} </p>
        <p><strong>Ciudad: </strong>{{ object.ciudad_usuario}} </p>
        <p><strong>Estado: </strong>{{ object.estado_usuario}} </p>


        <a class= "btn btn-danger" href="{% url 'perfil_usuario:perfil_listar' %}">Ok</a>
        <a class= "btn btn-info" href="{% url 'perfil_usuario:perfil_modificar' perfil_usuario.idperfil %}"><i class="material-icons">create</i></a>
        <a class="btn btn-success" href="{%  url 'perfil_usuario:perfil_eliminar' perfil_usuario.idperfil %}"><i class="material-icons">delete</i></a>
    </div>
</div>



{% endblock %}