apps/crud_simulador/urls.py
from django.conf.urls import url
from apps.crud_simulador.views import perfilCreate, perfilList, perfilUpdate, perfilDelete, perfilShow, search, mocvCreate,mocvList,mocvDelete,mocvShow,mocvUpdate,buscarxd\
    ,datos_empresaCreate, datos_empresaList, datos_empresaDelete, datos_empresaUpdate,datos_empresaShow, searchluis, manoObraCreate,manoObralist,manoObraDelete,manoObraUpdate\
    ,manoObraShow,conceptoCrecimientoDemandaCreate,conceptoCrecimientoDemandalist,conceptoCrecimientoDemandaDelete,conceptoCrecimientoDemandaUpdate, conceptoCrecimientoDemandaShow, searchluis2, searchluis3,\
    estimacion_serviciosCreate, estimacion_serviciosList,estimacion_serviciosDelete,estimacion_serviciosUpdate,estimacion_serviciosShow, tipoGastoOperativoCreate, tipoGastoOperativoList, tipoGastoOperativoDelete, tipoGastoOperativoUpdate, tipoGastoOperativoShow, searchever, searchever1\
    ,costosCreate,costosList,costosDelete,costosUpdate,costosShow,searchc,gastosCreate,gastosList,gastosDelete,gastosUpdate,gastosShow,findg\
    ,productoCreate,productoList,productoDelete,productoUpdate,productoShow,buscaP,gastossCreate,gastossList,gastossDelete,gastossUpdate,gastossShow,search_g\
    ,crecimientoDemandaCreate,crecimientoDemandaList,crecimientoDemandaDelete,crecimientoDemandaUpdate,crecimientoDemandaShow,search_c\
    ,tipoUsuarioCreate,tipoUsuarioList,tipoUsuarioDelete,tipoUsuarioUpdate,tipoUsuarioShow, search_u,gastosIndirectosCreate,gastosIndirectosList,gastosIndirectosDelete,gastosIndirectosUpdate,gastosIndirectosShow,search_a\
    ,tiposGastoscreate,tiposGastosList,tiposGastosDelete,tiposGastosUpdate,tiposGastosShow,search_b,usuarioCreate,usuarioList,usuarioDelete,usuarioShow,usuarioUpdate,search_tg, materiaPrimaCreate, materiaPrimaList,materiaPrimaDelete,materiaPrimaShow,materiaPrimaUpdate,search_ma,estimacionCreate\
    ,estimacionList,estimacionDelete,estimacionShow,estimacionUpdate,search_es,tiposInversionesCreate,tiposInversionesList,tiposInversionesDelete,tiposInversionesUpdate,tiposInversionesShow,search_ti

urlpatterns = [
    #urls de alex perfil usuario y mano de obra comision venta
    url(r'^crear/', perfilCreate.as_view(), name='perfil_crear'),
    url(r'^listar/', perfilList.as_view(), name='perfil_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', perfilDelete.as_view(), name='perfil_eliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', perfilUpdate.as_view(), name='perfil_modificar'),
    url(r'^mostrar/(?P<pk>\d+)/$', perfilShow.as_view(), name='perfil_mostrar'),
    url(r'^buscar/$', search, name='perfil_buscar'),

    url(r'^create/',mocvCreate.as_view(), name='mocv_create'),
    url(r'^list/', mocvList.as_view(), name='mocv_list'),
    url(r'^delete/(?P<pk>\d+)/$', mocvDelete.as_view(), name='mocv_delete'),
    url(r'^update/(?P<pk>\d+)/$', mocvUpdate.as_view(), name='mocv_update'),
    url(r'^show/(?P<pk>\d+)/$', mocvShow.as_view(), name='mocv_show'),
    url(r'^search/$', buscarxd, name='mocv_search'),

    #urls de luis david
    url(r'^crearempresa/', datos_empresaCreate.as_view(), name='datos_empresa_crear'),
    url(r'^listarempresa/', datos_empresaList.as_view(), name='datos_empresa_listar'),
    url(r'^eliminarempresa/(?P<pk>\d+)/$', datos_empresaDelete.as_view(), name='datos_empresa_eliminar'),
    url(r'^editarempresa/(?P<pk>\d+)/$', datos_empresaUpdate.as_view(), name='datos_empresa_editar'),
    url(r'^mostrarempresa/(?P<pk>\d+)/$', datos_empresaShow.as_view(), name='datos_empresa_mostrar'),
    url(r'^buscarempresa/$', searchluis, name='datos_empresa_buscar'),

    url(r'^crearobra/', manoObraCreate.as_view(), name='manoObra_crear'),
    url(r'^guardarobra/', manoObralist.as_view(), name='manoObra_listar'),
    url(r'^eliminarobra/(?P<pk>\d+)/$', manoObraDelete.as_view(), name='manoObra_eliminar'),
    url(r'^modificarobra/(?P<pk>\d+)/$', manoObraUpdate.as_view(), name='manoObra_editar'),
    url(r'^observarobra/(?P<pk>\d+)/$', manoObraShow.as_view(), name='manoObra_mostrar'),
    url(r'^investigarobra/$', searchluis2, name='manoObra_buscar'),

    url(r'^nuevosccd/', conceptoCrecimientoDemandaCreate.as_view(), name='conceptoCrecimientoDemanda_crear'),
    url(r'^listasccd/', conceptoCrecimientoDemandalist.as_view(), name='conceptoCrecimientoDemanda_listar'),
    url(r'^eliminacionccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaDelete.as_view(), name='conceptoCrecimientoDemanda_eliminar'),
    url(r'^modificacionccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaUpdate.as_view(), name='conceptoCrecimientoDemanda_editar'),
    url(r'^verccd/(?P<pk>\d+)/$', conceptoCrecimientoDemandaShow.as_view(), name='conceptoCrecimientoDemanda_mostrar'),
    url(r'^buscadorccd/$', searchluis3, name='conceptoCrecimientoDemanda_buscar'),

    #Urls de Everardo
    url(r'^nuevoservicio/', estimacion_serviciosCreate.as_view(), name='estimacion_servicio_crear'),
    url(r'^listarservicio/', estimacion_serviciosList.as_view(), name='estimacion_servicio_listar'),
    url(r'^eliminarservicio/(?P<pk>\d+)/$', estimacion_serviciosDelete.as_view(), name='estimacion_servicio_eliminar'),
    url(r'^modificarservicio/(?P<pk>\d+)/$', estimacion_serviciosUpdate .as_view(), name='estimacion_servicio_editar'),
    url(r'^mostrarservicio/(?P<pk>\d+)/$', estimacion_serviciosShow.as_view(), name='estimacion_servicio_mostrar'),
    url(r'^buscarservicio/', searchever, name='estimacion_servicio_buscar'),

    url(r'^newtgasto/',tipoGastoOperativoCreate.as_view(), name='tipoGastoOperativo_crear'),
    url(r'^listgasto/',tipoGastoOperativoList.as_view(), name='tipoGastoOperativo_listar'),
    url(r'^deletegasto/(?P<pk>\d+)/$',tipoGastoOperativoDelete.as_view(), name='tipoGastoOperativo_eliminar'),
    url(r'^updategasto/(?P<pk>\d+)/$',tipoGastoOperativoUpdate.as_view(), name='tipoGastoOperativo_editar'),
    url(r'^showgasto/(?P<pk>\d+)/$',tipoGastoOperativoShow.as_view(), name='tipoGastoOperativo_mostrar'),
    url(r'^searchgasto/$', searchever1, name='tipoGastoOperativo_buscar'),

 #urls de carmen
    url(r'^nuevoC/', costosCreate.as_view(), name='costos_crear'),
    url(r'^listarC/', costosList.as_view(), name='costos_listar'),
    url(r'^eliminarC/(?P<pk>\d+)/$', costosDelete.as_view(), name='costos_eliminar'),
    url(r'^modificarC/(?P<pk>\d+)/$', costosUpdate.as_view(), name='costos_editar'),
    url(r'^mostrarC/(?P<pk>\d+)/$', costosShow.as_view(), name='costos_mostrar'),
    url(r'^buscarC/$', searchc, name='costos_buscar'),

    url(r'^nuevoG/', gastosCreate.as_view(), name='gastos_crear'),
    url(r'^listarG/', gastosList.as_view(), name='gastos_listar'),
    url(r'^eliminarG/(?P<pk>\d+)/$', gastosDelete.as_view(), name='gastos_eliminar'),
    url(r'^modificarG/(?P<pk>\d+)/$', gastosUpdate.as_view(), name='gastos_editar'),
    url(r'^mostrarG/(?P<pk>\d+)/$', gastosShow.as_view(), name='gastos_mostrar'),
    url(r'^buscarG/$', findg, name='gastos_buscar'),

    url(r'^nuevoP/', productoCreate.as_view(), name='producto_crear'),
    url(r'^listarP/', productoList.as_view(), name='producto_listar'),
    url(r'^eliminarP/(?P<pk>\d+)/$', productoDelete.as_view(), name='producto_eliminar'),
    url(r'^modificarP/(?P<pk>\d+)/$', productoUpdate.as_view(), name='producto_editar'),
    url(r'^mostrarP/(?P<pk>\d+)/$', productoShow.as_view(), name='producto_mostrar'),
    url(r'^buscarP/$', buscaP, name='producto_buscar'),

#Urls de Alan
    url(r'^nuevogastos/',gastossCreate.as_view(), name='gastoss_crear'),
    url(r'^listargastos/',gastossList.as_view(),name='gastoss_listar'),
    url(r'^eliminargastos/(?P<pk>\d+)/$', gastossDelete.as_view(), name='gastoss_eliminar'),
    url(r'^editargastos/(?P<pk>\d+)/$', gastossUpdate.as_view(), name='gastoss_editar'),
    url(r'^mostrargastos/(?P<pk>\d+)/$', gastossShow.as_view(), name='gastoss_mostrar'),
    url(r'^buscargastos/$', search_g, name='gastoss_buscar'),

    url(r'^newcrecimiento/',crecimientoDemandaCreate.as_view(), name='crecimientoDemanda_crear'),
    url(r'^listcrecimiento/',crecimientoDemandaList.as_view(),name='crecimientoDemanda_listar'),
    url(r'^deletecrecimiento/(?P<pk>\d+)/$', crecimientoDemandaDelete.as_view(), name='crecimientoDemanda_eliminar'),
    url(r'^updatecrecimiento/(?P<pk>\d+)/$', crecimientoDemandaUpdate.as_view(), name='crecimientoDemanda_editar'),
    url(r'^showcrecimiento/(?P<pk>\d+)/$', crecimientoDemandaShow.as_view(), name='crecimientoDemanda_mostrar'),
    url(r'^searchcrecimiento/$', search_c, name='crecimientoDemanda_buscar'),

    url(r'^nuevostipou/',tipoUsuarioCreate.as_view(), name='tipoUsuario_crear'),
    url(r'^listastipou/',tipoUsuarioList.as_view(),name='tipoUsuario_listar'),
    url(r'^eliminaciontipou/(?P<pk>\d+)/$', tipoUsuarioDelete.as_view(), name='tipoUsuario_eliminar'),
    url(r'^modificartipou/(?P<pk>\d+)/$', tipoUsuarioUpdate.as_view(), name='tipoUsuario_editar'),
    url(r'^vertipou/(?P<pk>\d+)/$', tipoUsuarioShow.as_view(), name='tipoUsuario_mostrar'),
    url(r'^buscadortipou/$', search_u, name='tipoUsuario_buscar'),

#Urls de Emmanuel

url(r'^nuevoGI/', gastosIndirectosCreate.as_view(), name='gastosIndirectos_crear'),
    url(r'^listaGI/', gastosIndirectosList.as_view(), name='gastosIndirectos_listar'),
    url(r'^eliminarGI/(?P<pk>\d+)/$', gastosIndirectosDelete.as_view(), name='gastosIndirectos_eliminar'),
    url(r'^editaGI/(?P<pk>\d+)/$', gastosIndirectosUpdate.as_view(), name='gastosIndirectos_editar'),
    url(r'^mostrarGI/(?P<pk>\d+)/$', gastosIndirectosShow.as_view(), name='gastosIndirectos_mostrar'),
    url(r'^buscarGI/$', search_a, name='gastosIndirectos_buscar'),

    url(r'^nuevostg/', tiposGastoscreate.as_view(), name='tiposGastos_crear'),
    url(r'^listartg/', tiposGastosList.as_view(), name='tiposGastos_listar'),
    url(r'^eliminarrtg/(?P<pk>\d+)/$', tiposGastosDelete.as_view(), name='tiposGastos_eliminar'),
    url(r'^editartg/(?P<pk>\d+)/$', tiposGastosUpdate.as_view(), name='tiposGastos_editar'),
    url(r'^mostratg/(?P<pk>\d+)/$', tiposGastosShow.as_view(), name='tiposGastos_mostrar'),

simulador/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^perfil/', include(('apps.crud_simulador.urls', 'apps'), namespace='perfil_usuario')),
    url(r'^mcomisiones/', include(('apps.crud_simulador.urls', 'apps'), namespace='mcomisiones')),

    #urls de luis xD
    url(r'^datos_empresa/',include(('apps.crud_simulador.urls', 'apps'), namespace='datos_empresa')),
    url(r'^manoObra/',include(('apps.crud_simulador.urls', 'apps'), namespace='manoObra')),
    url(r'^demanda/',include(('apps.crud_simulador.urls', 'apps'), namespace='demanda')),

    #urls de Ever xD
    url(r'^estimacion_servicios/', include(('apps.crud_simulador.urls', 'apps'), namespace='estimacion_servicios')),
    url(r'^tipoGastoOperativo/', include(('apps.crud_simulador.urls', 'apps'), namespace='tipoGastoOperativo')),

 #urls de carmen
    url(r'^costos/', include(('apps.crud_simulador.urls', 'apps'), namespace='costos')),
    url(r'^gastos/', include(('apps.crud_simulador.urls', 'apps'), namespace='gastos')),
    url(r'^producto/', include(('apps.crud_simulador.urls', 'apps'), namespace='producto')),
   #Urls de Alan
    url(r'^gastoss/',include(('apps.crud_simulador.urls','apps',),namespace='gastoss')),
    url(r'^crecimientoDemanda/', include(('apps.crud_simulador.urls', 'apps',), namespace='crecimientoDemanda')),
    url(r'^tipoUsuario/', include(('apps.crud_simulador.urls', 'apps',), namespace='tipoUsuario')),

#urls de Emmanuel

    url(r'^gastosIndirectos/', include(('apps.crud_simulador.urls', 'apps'), namespace='gastosIndirectos')),
    url(r'^usuario/', include(('apps.crud_simulador.urls', 'apps'), namespace='usuario')),
    url(r'^tiposGastos/', include(('apps.crud_simulador.urls', 'apps'), namespace='tiposGastos')),

#urls de aldair
    url(r'^tiposInversiones/', include(('apps.crud_simulador.urls', 'apps'), namespace='tiposInversiones')),
    url(r'^materiaPrima/', include(('apps.crud_simulador.urls', 'apps'), namespace='materiaPrima')),
    url(r'^estimacion/', include(('apps.crud_simulador.urls', 'apps'), namespace='estimacion')),
]

templates/crud_costos/Costos_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn" href="{% url 'costos:costos_listar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crud_costos/costos_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
	        <thead>
		        <tr>
			        <td>idcostosTotalesAnuales</td>
			        <td>anio</td>
			        <td>tiposGastoss</td>
                    <td>datos_empresa_id_empresa</td>
                </tr>
            </thead>
            <tbody>
		        {% if object_list %}
		        {% for costos in object_list %}
		        <tr>
			        <td>{{ costos.idcostosTotalesAnuales }}</td>
			        <td>{{ costos.anio }}</td>
			        <td>{{ costos.tiposGastoss }}</td>
			        <td>{{ costos.datos_empresa_id_empresa }}</td>
			        <td>
				        <a class="btn" href="{% url 'costos:costos_mostrar' costos.idcostosTotalesAnuales %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'costos:costos_editar' costos.idcostosTotalesAnuales %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'costos:costos_eliminar' costos.idcostosTotalesAnuales %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de costos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crud_costos/costos_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
                idcostosTotalesAnuales: &nbsp{{ filter.form.idcostosTotalesAnuales }} &nbsp
                anio: &nbsp {{ filter.form.anio }} &nbsp;&nbsp;&nbsp;
                <button class="btn blue" type="submit">Filtrar</button>
            </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <td>id costos Totales Anuales</td>
			        <td>año</td>
			        <td>tipos de gastos</td>
                    <td>datos empresa_id empresa</td>
                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for costosTotalesAnuales in filter.qs %}
		        <tr>
			        <td>{{ costosTotalesAnuales.idcostosTotalesAnuales }}</td>
			        <td>{{ costosTotalesAnuales.anio }}</td>
			        <td>{{ costosTotalesAnuales.tiposGastoss }}</td>
			        <td>{{ costosTotalesAnuales.datos_empresa_id_empresa }}</td>
			        <td>
				        <a class="btn" href="{% url 'costos:costos_mostrar' costosTotalesAnuales.idcostosTotalesAnuales %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'costos:costos_editar' costosTotalesAnuales.idcostosTotalesAnuales %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'costos:costos_eliminar' costosTotalesAnuales.idcostosTotalesAnuales %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de costos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crud_costos/costos_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>idcostosTotalesAnuales: </strong>{{ object.idcostosTotalesAnuales }} </p>
        <p><strong>anio: </strong>{{ object.anio }} </p>
        <p><strong>tiposGastoss: </strong>{{ object.tiposGastoss }} </p>
        <p><strong>datos_empresa_id_empresa: </strong>{{ object.datos_empresa_id_empresa }} </p>

        <a class= "btn" href="{% url 'costos:costos_listar' %}">Ok</a>
        <a class= "btn blue" href="{% url 'costos:costos_editar' object.idcostosTotalesAnuales %}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'costos:costos_eliminar' object.idcostosTotalesAnuales %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/crud_costos/gastos_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
	        <thead>
		        <tr>
			        <td>id tipos Gastoss</td>
			        <td>concepto</td>
                </tr>
            </thead>
            <tbody>
            {% if object_list %}
                {% for tiposGastoss in object_list %}
		        <tr>
			        <td>{{ tiposGastoss.idtiposGastoss }}</td>
			        <td>{{ tiposGastoss.concepto }}</td>
			        <td>
				        <a class="btn" href="{% url 'gastos:gastos_mostrar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'gastos:gastos_editar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'gastos:gastos_eliminar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de gastos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crud_costos/gastos_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
                id tipos Gastoss : &nbsp{{ filter.form.idtiposGastoss}} &nbsp
                concepto : &nbsp {{ filter.form.concepto }} &nbsp;&nbsp;&nbsp;
                <button class="btn blue" type="submit">Filtrar</button>
            </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <td>id tipos Gastoss</td>
			        <td>concepto</td>
                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for tiposGastoss in filter.qs %}
		        <tr>
			        <td>{{ tiposGastoss.idtiposGastoss }}</td>
			        <td>{{ tiposGastoss.concepto }}</td>
			        <td>
				        <a class="btn" href="{% url 'gastos:gastos_mostrar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'gastos:gastos_editar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'gastos:gastos_eliminar' tiposGastoss.idtiposGastoss %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de gastos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crud_costos/producto_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
	        <thead>
		        <tr>
			        <td>id producto</td>
			        <td>producto nombre</td>
                    <td>unidad produccion</td>
			        <td>produccion mensual</td>
                    <td>costo unitario</td>
			        <td>margen utilidad</td>
                    <td>precio publico</td>
			        <td>Datos empresa</td>

                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for producto_servicio in filter.qs %}
		        <tr>
                    <td>{{ producto_servicio.id_producto }} </td>
                    <td>{{ producto_servicio.producto_nombre }} </td>
                    <td>{{ producto_servicio.unidad_produccion }}</td>
                    <td>{{ producto_servicio.produccion_mensual }}</td>
                    <td>{{ producto_servicio.costo_unitario }}</td>
                    <td>{{ producto_servicio.margen_utilidad }}</td>
                    <td>{{ producto_servicio.precio_publico }}</td>
                    <td>{{ producto_servicio.datos_empresa_id_empresa }}</td>
			        <td>
				        <a class="btn" href="{% url 'producto:producto_mostrar' producto_servicio.id_producto %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'producto:producto_editar' producto_servicio.id_producto %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'producto:producto_eliminar' producto_servicio.id_producto %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de productos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crud_costos/producto_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>id producto: </strong>{{ object.id_producto }} </p>
        <p><strong>producto nombre: </strong>{{ object.producto_nombre }} </p>
        <p><strong>unidad produccion: </strong>{{ object.unidad_produccion }} </p>
        <p><strong>produccion mensual: </strong>{{ object.produccion_mensual }} </p>
        <p><strong>costo unitario: </strong>{{ object.costo_unitario }} </p>
        <p><strong>margen utilidad: </strong>{{ object.margen_utilidad }} </p>
        <p><strong>precio publico: </strong>{{ object.precio_publico }} </p>
        <p><strong>Datos empresa id empresa: </strong>{{ object.datos_empresa_id_empresa }} </p>

        <a class= "btn" href="{% url 'producto:producto_listar' %}">Ok</a>
        <a class="btn blue" href="{% url 'producto:producto_editar' producto_servicio.id_producto %}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'producto:producto_eliminar' producto_servicio.id_producto %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}